[Interface]
PrivateKey = iDgHylDXkwKVsqB3JhaHPjsU+k5d1TFf6awCxeVcVkA=
Address = 10.0.0.1/24
ListenPort = 51820
Table = off

PostUp   = sysctl -w net.ipv4.ip_forward=1
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp   = iptables -A FORWARD -o wg0 -j ACCEPT
PostUp   = iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o enp1s0 -j MASQUERADE
PostDown = sysctl -w net.ipv4.ip_forward=0
PostDown = iptables -F FORWARD
PostDown = iptables -t nat -F POSTROUTING
        

[Peer]
PublicKey = SQNasweymGDhQhgQhHHjAGix74INPibewhIxVK4xUz4=
AllowedIPs = 10.0.0.2/32
Endpoint = 158.247.246.229:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = 6hDWcnWX8oSxdGlRTGx7XIHYD4CTb7FaPNbMlO2l51M=
AllowedIPs = 10.0.0.3/32
Endpoint = 149.28.166.245:51820
PersistentKeepalive = 200