[Interface]
PrivateKey = 0BKtWulPIWoWsH4us1vhrJrS6rTsV5GT3yLWRY3sV2I=
Address = 10.0.0.14/24
ListenPort = 51820
Table = off

PostUp   = sysctl -w net.ipv4.ip_forward=1
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp   = iptables -A FORWARD -o wg0 -j ACCEPT
PostUp   = iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o enp1s0 -j MASQUERADE
PostDown = sysctl -w net.ipv4.ip_forward=0
PostDown = iptables -F FORWARD
PostDown = iptables -t nat -F POSTROUTING
        

[Peer]
PublicKey = G4ll9JWGIQX7w+SDtATpnwaQx3HUXBDA1CKi9E1JnVw=
AllowedIPs = 10.0.0.1/32
Endpoint = 45.76.199.202:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = 6KWZGx/RAjjZhKyqCYvD7/f3+e9Ukus1SCN0k+WbBgk=
AllowedIPs = 10.0.0.2/32
Endpoint = 158.247.246.229:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = XiWP02nYWFkNgABzpFArZiiY32KFP2fxF/gWNTbnGDU=
AllowedIPs = 10.0.0.3/32
Endpoint = 149.28.133.181:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = FlqSZX8RG2cNkEROdMCiwkaNQxTb8gC5lSJDi7BHzQk=
AllowedIPs = 10.0.0.4/32
Endpoint = 64.177.66.138:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = cK+h5DAZnwZ2rmZ0ips9aG5qcZ6kc0xBbE7Sar8RNCQ=
AllowedIPs = 10.0.0.5/32
Endpoint = 65.20.75.125:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = 5ILrDlRMJu+/APzVSEcWokvApsqMpiqK55CA8z5PrBM=
AllowedIPs = 10.0.0.6/32
Endpoint = 136.244.70.245:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = DyMlTFT9zwUPJ7cXSfnvjWzTZMTRuTmT2DSVnqR7Bkg=
AllowedIPs = 10.0.0.7/32
Endpoint = 217.69.4.120:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = lC4sGWyCxlHaPIa88Po2+qE1eXQxkx2475t8dMsHpUc=
AllowedIPs = 10.0.0.8/32
Endpoint = 64.176.73.20:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = SfszX7ohljDA7QGXETtSwL/b/hQhsYvWWHPMM/Plm1k=
AllowedIPs = 10.0.0.9/32
Endpoint = 65.20.108.238:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = Waf1lLExIpELwBw0D5825pC/Gf5po03g+fIJpQj4924=
AllowedIPs = 10.0.0.10/32
Endpoint = 149.28.166.245:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = gIhTNgKDkYu8lZ8b3p2+5y6PaLvnqo2fSKc8ECI0txM=
AllowedIPs = 10.0.0.11/32
Endpoint = 149.248.59.209:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = F6D5slYEbjs7dF9QBFjHkMkYSTXacSoMoiB/to+PLCA=
AllowedIPs = 10.0.0.12/32
Endpoint = 216.238.69.50:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = baW4i9mi4etJvE0oPKP+59Ujs5CuEyQxqFlNp7kNJik=
AllowedIPs = 10.0.0.13/32
Endpoint = 216.238.100.62:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = Mz1MnfzQeZ+hH7fDHPNJN9jT6Yz0sHl/sTo9Kb/mIQw=
AllowedIPs = 10.0.0.15/32
Endpoint = 64.176.6.188:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = HpIZ3UCAYVdMe3sFR1jNckW8hDkNi0B7wbDpYGfN/nY=
AllowedIPs = 10.0.0.16/32
Endpoint = 139.84.235.124:51820
PersistentKeepalive = 200