pid = /var/run/stunnel4.pid
cert = /etc/stunnel/stunnel.pem
# 前台不运行，启用后台模式
foreground = no

[http_proxy]
accept = 0.0.0.0:443      # 服务端监听的加密端口
connect = 127.0.0.1:1081  # 最终要转发到的本地目标服务端口

[socks5]
accept = 0.0.0.0:8443      # 服务端监听的加密端口
connect = 127.0.0.1:1082  # 最终要转发到的本地目标服务端口