[Interface]
PrivateKey = EOBsBxLTkf+6v5OaOCaxf3GJgwzpru9R7/CcdRsmfVQ=
Address = 10.0.0.2/24
ListenPort = 51820
FwMark = 51820
Table = off

PostUp   = sysctl -w net.ipv4.ip_forward=1
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp   = iptables -A FORWARD -o wg0 -j ACCEPT
PostUp   = iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o enp1s0 -j MASQUERADE
PostDown = sysctl -w net.ipv4.ip_forward=0
PostDown = iptables -F FORWARD
PostDown = iptables -t nat -F POSTROUTING
        

[Peer]
PublicKey = NkuX71uR/UcX/QPOEdML6hyU0VRZE6Rp6G3z3PIZ4ik=
AllowedIPs = 10.0.0.1/32
Endpoint = 136.244.70.245:51820
PersistentKeepalive = 200        

[Peer]
PublicKey = 6hDWcnWX8oSxdGlRTGx7XIHYD4CTb7FaPNbMlO2l51M=
AllowedIPs = 10.0.0.3/32
Endpoint = 149.28.166.245:51820
PersistentKeepalive = 200